// Generated from the Rust commands, events and constants by `cargo test bindings`; change those instead.
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	extractWaveform: () => __TAURI_INVOKE<Waveform>("extract_waveform"),
	chooseComponent: (name: string, path: string) => __TAURI_INVOKE<ComponentStatus[]>("choose_component", { name, path }),
	forgetComponent: (name: string) => __TAURI_INVOKE<ComponentStatus[]>("forget_component", { name }),
	componentStatuses: () => __TAURI_INVOKE<ComponentStatus[]>("component_statuses"),
	modelSettings: () => __TAURI_INVOKE<ModelSettingsView>("model_settings"),
	chooseModel: (slot: ModelSlot, source: ModelSource) => __TAURI_INVOKE<ModelSettingsView>("choose_model", { slot, source }),
	presetModels: (slot: ModelSlot) => __TAURI_INVOKE<PresetModel[]>("preset_models", { slot }),
	downloadModel: (repo: string, file: string, revision: string | null) => __TAURI_INVOKE<ModelSource>("download_model", { repo, file, revision }),
	repositoryFiles: (repo: string, slot: ModelSlot) => __TAURI_INVOKE<RepositoryFile[]>("repository_files", { repo, slot }),
	cancelModelDownload: (repo: string, file: string) => __TAURI_INVOKE<void>("cancel_model_download", { repo, file }),
	transcribe: (overwrite: boolean, scope: TranscriptionScope) => __TAURI_INVOKE<Transcription>("transcribe", { overwrite, scope }),
	diarize: () => __TAURI_INVOKE<Diarization>("diarize"),
	transcriptionSettings: () => __TAURI_INVOKE<TranscriptionSettings>("transcription_settings"),
	saveTranscriptionSettings: (settings: TranscriptionSettings) => __TAURI_INVOKE<TranscriptionSettings>("save_transcription_settings", { settings }),
	preferences: () => __TAURI_INVOKE<Preferences>("preferences"),
	savePreferences: (preferences: Preferences) => __TAURI_INVOKE<Preferences>("save_preferences", { preferences }),
	currentProject: () => __TAURI_INVOKE<{
	directory: string,
	name: string,
	/**  The name the Project takes from its directory without a Project Name of its own. */
	directory_name: string,
	language: Language,
	translation_language: Language | null,
	options: ProjectOptions_Serialize,
	translation_glossary: TranslationGlossaryView | null,
	resources: ResourceView[],
	current_resource: string | null,
	media: string | null,
	segments: Segment_Serialize[],
	/**  The Glossary Marks of each of `segments`. */
	glossary_marks: SegmentGlossaryMarks[],
	shown_translation: Language | null,
	/**
	 *  What the Translation Glossary calls each Speaker in the translation shown, by its name in
	 *  the Primary Language, so the webview names a Speaker as the saved subtitle does.
	 */
	shown_speaker_names: { [key in string]: string },
	has_undo: boolean,
	has_redo: boolean,
	running_mode: RunningMode | null,
	pending_batch: SegmentSpan | null,
	/**
	 *  Which Preset Model each Project Model is; the Preset Models belong to the toolchain, so the
	 *  command answering the view fills this in.
	 */
	project_model_presets: ProjectModelPresets,
} | null>("current_project"),
	editSegment: (index: number, field: SegmentField, value: string) => __TAURI_INVOKE<null>("edit_segment", { index, field, value }),
	setSpeakers: (indexes: number[], speaker: string) => __TAURI_INVOKE<null>("set_speakers", { indexes, speaker }),
	replaceText: (field: SegmentField, replacement: Replacement) => __TAURI_INVOKE<number>("replace_text", { field, replacement }),
	cleanSimplified: (scope: CleanupScope) => __TAURI_INVOKE<number>("clean_simplified", { scope }),
	findText: (field: SegmentField, search: Search) => __TAURI_INVOKE<TextMatch[]>("find_text", { field, search }),
	cancelTask: () => __TAURI_INVOKE<void>("cancel_task"),
	retranslate: (indexes: number[], options: TranslationOptions) => __TAURI_INVOKE<Translation>("retranslate", { indexes, options }),
	changeSegments: (change: SegmentChange) => __TAURI_INVOKE<null>("change_segments", { change }),
	translationCues: (language: Language) => __TAURI_INVOKE<ComparedCue[]>("translation_cues", { language }),
	logDirectory: () => __TAURI_INVOKE<LogDirectory>("log_directory"),
	chooseLogDirectory: (path: string) => __TAURI_INVOKE<LogDirectory>("choose_log_directory", { path }),
	debugLog: () => __TAURI_INVOKE<DebugLog>("debug_log"),
	chooseDebugLog: (hasDebugLog: boolean) => __TAURI_INVOKE<DebugLog>("choose_debug_log", { hasDebugLog }),
	openLogDirectory: () => __TAURI_INVOKE<null>("open_log_directory"),
	appBuild: () => __TAURI_INVOKE<AppBuild>("app_build"),
	openReleases: () => __TAURI_INVOKE<null>("open_releases"),
	openSponsorship: () => __TAURI_INVOKE<null>("open_sponsorship"),
	checkForUpdate: () => __TAURI_INVOKE<{
	release_number: string,
	release_name: string,
	is_preview_build: boolean,
} | null>("check_for_update"),
	checkForUpdateAtLaunch: () => __TAURI_INVOKE<{
	release_number: string,
	release_name: string,
	is_preview_build: boolean,
} | null>("check_for_update_at_launch"),
	installUpdate: () => __TAURI_INVOKE<null>("install_update"),
	updateSettings: () => __TAURI_INVOKE<UpdateSettings>("update_settings"),
	chooseLaunchCheck: (hasLaunchCheck: boolean) => __TAURI_INVOKE<UpdateSettings>("choose_launch_check", { hasLaunchCheck }),
	chooseUpdateChannel: (channel: UpdateChannel) => __TAURI_INVOKE<UpdateSettings>("choose_update_channel", { channel }),
	checkForRollback: () => __TAURI_INVOKE<{
	release_number: string,
	release_name: string,
	is_preview_build: boolean,
} | null>("check_for_rollback"),
	revertRow: (language: "zh-TW" | "en" | "ja" | null, backup: string, row: number, part: RevertPart) => __TAURI_INVOKE<Restoration>("revert_row", { language, backup, row, part }),
	undo: () => __TAURI_INVOKE<null>("undo"),
	redo: () => __TAURI_INVOKE<null>("redo"),
	subtitleVersions: () => __TAURI_INVOKE<SubtitleVersions[]>("subtitle_versions"),
	compareVersions: (language: "zh-TW" | "en" | "ja" | null, left: string | null, right: string | null) => __TAURI_INVOKE<ComparedRow[]>("compare_versions", { language, left, right }),
	restoreVersion: (language: "zh-TW" | "en" | "ja" | null, backup: string) => __TAURI_INVOKE<Restoration>("restore_version", { language, backup }),
	exportPath: (content: WrittenText, format: ExportFormat) => __TAURI_INVOKE<string>("export_path", { content, format }),
	openProject: (path: string, language: Language) => __TAURI_INVOKE<null>("open_project", { path, language }),
	openSrt: (path: string, language: Language) => __TAURI_INVOKE<null>("open_srt", { path, language }),
	recentProjects: () => __TAURI_INVOKE<RecentProjectView[]>("recent_projects"),
	takeRequestedSrt: () => __TAURI_INVOKE<string | null>("take_requested_srt"),
	saveSrt: (path: string, content: WrittenText) => __TAURI_INVOKE<null>("save_srt", { path, content }),
	saveText: (path: string, content: WrittenText, hasSpeakers: boolean, hasBlankLines: boolean) => __TAURI_INVOKE<null>("save_text", { path, content, hasSpeakers, hasBlankLines }),
	selectResource: (name: string) => __TAURI_INVOKE<null>("select_resource", { name }),
	setPrimaryLanguage: (language: Language) => __TAURI_INVOKE<null>("set_primary_language", { language }),
	setProjectOptions: (options: ProjectOptions_Deserialize) => __TAURI_INVOKE<null>("set_project_options", { options }),
	showTranslation: (language: "zh-TW" | "en" | "ja" | null) => __TAURI_INVOKE<null>("show_translation", { language }),
	reloadProject: () => __TAURI_INVOKE<null>("reload_project"),
	/**  Saves the settings, stopping the Resident llama-server when it is turned off and starting it when turned on. */
	saveTranslationSettings: (settings: TranslationSettings) => __TAURI_INVOKE<TranslationSettings>("save_translation_settings", { settings }),
	translate: (target: Language, options: TranslationOptions) => __TAURI_INVOKE<Translation>("translate", { target, options }),
	translationSettings: () => __TAURI_INVOKE<TranslationSettings>("translation_settings"),
	saveTranslationGlossary: (rows: GlossaryRow[]) => __TAURI_INVOKE<null>("save_translation_glossary", { rows }),
	translationGlossaryTable: () => __TAURI_INVOKE<GlossaryTable>("translation_glossary_table"),
};

/** Events */
export const events = {
	changedElsewhereKept: makeEvent<ChangedElsewhereKept>("changed-elsewhere-kept"),
	editCommand: makeEvent<EditCommand>("edit-command"),
	modelDownloadProgress: makeEvent<ModelDownloadProgress>("model-download-progress"),
	pipelineProgress: makeEvent<PipelineProgress_Deserialize>("pipeline-progress"),
	projectChanged: makeEvent<ProjectChanged>("project-changed"),
	srtRequested: makeEvent<SrtRequested>("srt-requested"),
	updateProgress: makeEvent<AppUpdateProgress>("update-progress"),
	videoWindowClosing: makeEvent<VideoWindowClosing>("video-window-closing"),
};

/* Constants */
export const DEFAULT_PREFERENCES = {"choice_landings":{"text":{"is_pausing":true,"is_from_start":true},"time":{"is_pausing":true,"is_from_start":true},"speaker":{"is_pausing":false,"is_from_start":false},"row":{"is_pausing":true,"is_from_start":true},"next":{"is_pausing":false,"is_from_start":false},"region":{"is_pausing":false,"is_from_start":false},"search":{"is_pausing":true,"is_from_start":true}}} as const;

export const VIDEO_WINDOW = "video" as const;

/* Types */
/**
 *  The App Build: the release number of the running Tsuzuri with its Release Name, whether it is a
 *  Preview build, whether its install offers the Preview channel, and the commit it was built from.
 */
export type AppBuild = {
	release_number: string,
	release_name: string,
	is_preview_build: boolean,
	has_preview_channel: boolean,
	commit: string,
};

/**  The App Update a check found, as the webview shows it: by its Release Name. */
export type AppUpdate = {
	release_number: string,
	release_name: string,
	is_preview_build: boolean,
};

/**  How much of the App Update being installed has downloaded. */
export type AppUpdateProgress = UpdateProgress;

/**  A Backup of one subtitle, by its file name in the history, the UTC time it was taken and its kind. */
export type Backup = {
	file: string,
	/**  `YYYYMMDDTHHMMSSZ` */
	taken_at: string,
	kind: BackupKind,
};

/**  What a Backup keeps: what a Mode has just written, or a subtitle just before it was written over. */
export type BackupKind = "output" | "overwrite";

/**  Which text a Bilingual SRT puts first in each cue and in its file name. */
export type BilingualOrder = "original-first" | "translation-first";

/**
 *  A subtitle changed elsewhere was read again, and what Tsuzuri last held of it kept as an
 *  Overwrite Backup.
 */
export type ChangedElsewhereKept = null;

/**
 *  What playing media does as another Segment is chosen from one Choice Source: whether it
 *  pauses, and whether it moves to the Segment's start or stays where it is, which for a region is
 *  where it was clicked.
 */
export type ChoiceLanding = {
	is_pausing: boolean,
	is_from_start: boolean,
};

/**  The Choice Landing of each Choice Source. */
export type ChoiceLandings = {
	/**  A Segment's text or translation. */
	text?: ChoiceLanding,
	/**  A time of a Segment. */
	time?: ChoiceLanding,
	speaker?: ChoiceLanding,
	/**  Anywhere else in a Segment's row, or the keyboard's focus reaching it. */
	row?: ChoiceLanding,
	/**  Enter moving on from the field before. */
	next?: ChoiceLanding,
	region?: ChoiceLanding,
	search?: ChoiceLanding,
};

/**  Where a Simplified Cleanup cleans the Current Resource's `zh-TW` text. */
export type CleanupScope = 
/**  The Segments at these positions. */
{ kind: "segments"; indexes: number[] } | 
/**  Characters `start` to `end` of `field` of the Segment at `index`. */
{ kind: "range"; index: number; field: SegmentField; start: number; end: number };

/**  One cue of a Version as a Comparison Row shows it. */
export type ComparedCue = {
	start_ms: number,
	end_ms: number,
	text: string,
};

/**  The cues of two Versions that cover the same speech, and what changed between them. */
export type ComparedRow = {
	kind: RowKind,
	left: ComparedCue[],
	right: ComparedCue[],
	is_text_changed: boolean,
	is_time_changed: boolean,
	/**
	 *  For a Pair whose text changed, its text character by character: what both keep, what
	 *  only the earlier Version has, and what only the later one has.
	 */
	text_spans: TextSpan[],
};

export type ComponentStatus = {
	name: string,
	is_ready: boolean,
	path: string | null,
	origin: Origin | null,
	/**  The Bundled Variant Auto-Selection took, when that is where it was found. */
	variant: string | null,
	problem: Problem | null,
	install: string | null,
};

/**  How many of the things a Phase works through it has finished. */
export type Count = {
	done_count: number,
	total: number,
};

/**  Whether the Debug Log is written in this launch, and whether it is chosen for the next. */
export type DebugLog = {
	is_written_now: boolean,
	is_written_next_launch: boolean,
};

export type Diarization = {
	audio_seconds: number,
	diarize_seconds: number,
	phases: PhaseTiming[],
};

/**  How much of a Model being downloaded has arrived. */
export type DownloadProgress = {
	repo: string,
	file: string,
	downloaded: number,
	total: number | null,
};

/**
 *  Undo, Redo, Select All or Clean Simplified Chinese chosen from the Edit menu, which takes their
 *  shortcuts before the webview sees them; the webview knows what each applies to.
 */
export type EditCommand = "undo" | "redo" | "select-all" | "clean-simplified";

/**  The form an export of the Current Resource is written in. */
export type ExportFormat = "srt" | "plain_text";

/**
 *  Why a command did not finish. The webview words each code in the interface language,
 *  so a variant carries data rather than prose; `detail` is text a system or Component wrote.
 */
export type Failure = 
/**  Reading or writing a file failed. */
{ code: "io"; detail: string } | { code: "malformed-srt"; cue: number } | 
/**
 *  A Translation Glossary file whose header does not name a Language for each column, or is
 *  `source,target` while the Project has no translation Language to stand for `target`.
 */
{ code: "glossary-without-header" } | { code: "malformed-glossary"; detail: string } | { code: "model-not-chosen"; slot: ModelSlot } | { code: "model-missing"; path: string } | 
/**  A Repository's Model the Hugging Face Cache does not hold. */
{ code: "model-not-downloaded"; repo: string; file: string } | 
/**  Downloading a Model from Hugging Face went wrong. */
{ code: "model-download-failed"; detail: string } | 
/**  A Hugging Face Repository that needs a login, or access granted to the account logged in. */
{ code: "model-login-required"; repo: string } | 
/**  A Hugging Face Repository that does not exist, or is private to someone else. */
{ code: "repository-not-found"; repo: string } | 
/**  The Model's download was asked to stop. */
{ code: "model-download-cancelled" } | 
/**  The same file of a Repository asked to download while it already is. */
{ code: "model-downloading" } | 
/**  A directory asked to open as the Project that no longer exists. */
{ code: "directory-not-found"; directory: string } | 
/**  Translating, editing or saving asked for before a Project was opened. */
{ code: "no-project" } | 
/**  The Project has no Resource by the name asked for, or none is current. */
{ code: "no-resource" } | 
/**  The media file of a Current Resource that has none, asked for to convert it. */
{ code: "no-media" } | 
/**  A diarization asked of a Current Resource that has no Primary Language subtitle. */
{ code: "no-subtitle" } | 
/**
 *  An edit refused because a subtitle of the Current Resource was changed elsewhere since
 *  Tsuzuri last read or wrote it; the Current Resource was read again instead.
 */
{ code: "changed-elsewhere" } | 
/**
 *  A change refused because a Mode running on the Current Resource writes the subtitle it
 *  would change.
 */
{ code: "mode-running" } | 
/**  The running Mode was asked to stop. */
{ code: "mode-cancelled" } | 
/**  Translating again needs a translation shown to write into. */
{ code: "no-translation-shown" } | 
/**  A Simplified Cleanup with no text in `zh-TW` where it was asked for. */
{ code: "no-traditional-chinese" } | 
/**  A Segment Change that would leave a Segment ending before it starts. */
{ code: "invalid-times" } | 
/**
 *  A Segment Change that would start a Segment before the Segment before it or after the one
 *  after it.
 */
{ code: "unordered-times" } | 
/**  A Replacement with nothing to find, or a regular expression the `regex` crate cannot read. */
{ code: "invalid-pattern"; detail: string } | 
/**  A restore that named no Backup of the subtitle it was asked for. */
{ code: "no-backup"; backup: string } | 
/**  Taking back a Comparison Row the comparison no longer has, as after the subtitle changed. */
{ code: "no-row"; row: number } | 
/**  Transcribing over an original subtitle the user did not ask to overwrite. */
{ code: "subtitle-exists"; path: string } | { code: "component-not-ready"; component: string } | 
/**  A Step's process could not start or exited without success. */
{ code: "step-failed"; step: string; detail: string } | 
/**  Looking for, downloading, verifying or installing an App Update went wrong. */
{ code: "update-failed"; detail: string } | 
/**  Installing an App Update asked for before a check found one. */
{ code: "no-update" } | 
/**  Installing an App Update asked for while a Mode runs, whose Components installing stops. */
{ code: "update-during-mode" } | 
/**  Opening a Project asked for while a Mode runs, which writes into the Project open. */
{ code: "opening-during-mode" } | { code: "llama-exited" } | { code: "llama-timed-out" } | 
/**  llama-server answered a request with an error, or without a translation. */
{ code: "llama-request"; detail: string } | 
/**  Something that should not happen, such as a background task panicking. */
{ code: "internal"; detail: string };

/**
 *  A stretch of a field the editor underlines, from `start` to `end` in UTF-16 units, as the
 *  webview counts text.
 */
export type GlossaryMark = {
	start: number,
	end: number,
	/**  The words the stretch holds, as the field writes them. */
	word: string,
	kind: GlossaryMarkKind,
};

/**  What a Glossary Mark stands for; serialized in lowercase, as `term` or `candidate`. */
export type GlossaryMarkKind = 
/**  A term of the Translation Glossary. */
"term" | 
/**  A proper noun the Translation Glossary does not have. */
"candidate";

/**  One term: its word in each Language, and whether it names a Speaker. */
export type GlossaryRow = {
	words: string[],
	is_speaker: boolean,
};

/**  A Translation Glossary laid out for editing: a column for every Language and a row per term. */
export type GlossaryTable = {
	languages: Language[],
	rows: GlossaryRow[],
	/**  Whether its file has a `source,target` header, which saving rewrites as Language codes. */
	has_source_target_header: boolean,
};

/**  A language Tsuzuri transcribes from or translates into; the webview sends only its code. */
export type Language = "zh-TW" | "en" | "ja";

/**  The directory the log is written to in this launch, and the one chosen for the next. */
export type LogDirectory = {
	in_use: string,
	next_launch: string,
};

/**  How much of a Model being downloaded has arrived. */
export type ModelDownloadProgress = DownloadProgress;

export type ModelSettingsView = {
	transcription: SlotView,
	vad: SlotView,
	translation: SlotView,
	diarization: SlotView,
};

export type ModelSlot = "transcription" | "vad" | "translation" | "diarization";

/**  Where a Model Slot's Model comes from. */
export type ModelSource = { kind: "file"; path: string } | 
/**  A Hugging Face Repository's `file` downloaded at `commit`, kept in the Hugging Face Cache. */
{ kind: "repository"; repo: string; file: string; commit: string };

export type Origin = "choice" | "detection" | "bundled-variant";

/**  One timed part of a Mode's run, named in `pipeline-progress`, in the seconds each took and in the log. */
export type Phase = "prepare" | "convert" | "load" | "transcribe" | "diarize" | "detect" | "translate";

export type PhaseTiming = {
	phase: Phase,
	seconds: number,
};

/**  Sent as each Phase starts and as its percentage changes; a Phase that cannot tell how far along it is has no percentage. */
export type PipelineProgress = PipelineProgress_Serialize | PipelineProgress_Deserialize;

/**  Sent as each Phase starts and as its percentage changes; a Phase that cannot tell how far along it is has no percentage. */
export type PipelineProgress_Deserialize = {
	phase: Phase,
	percent: number | null,
	count: Count,
};

/**  Sent as each Phase starts and as its percentage changes; a Phase that cannot tell how far along it is has no percentage. */
export type PipelineProgress_Serialize = {
	phase: Phase,
	percent: number | null,
	count?: Count,
};

export type Preferences = {
	choice_landings?: ChoiceLandings,
};

/**  A Model Tsuzuri was verified with, offered by name so nobody has to know where to find it. */
export type PresetModel = {
	slot: ModelSlot,
	name: string,
	quantization: string,
	source: ModelSource,
	size: number,
};

/**  Why a Component is not ready. */
export type Problem = "not-installed" | 
/**  The Bundled Variant is there but fails its version flag, as when a driver it needs is missing. */
"does-not-run";

/**  The Project changed; the webview reads it again. */
export type ProjectChanged = null;

/**
 *  Which Preset Model each Project Model is, as its place among its slot's Preset Models; none
 *  where the slot has no Project Model or holds a Model that is none of them.
 */
export type ProjectModelPresets = {
	transcription: number | null,
	translation: number | null,
};

/**  The Project Models by the slot each is chosen for; a slot without one uses the general settings' Model. */
export type ProjectModels = ProjectModels_Serialize | ProjectModels_Deserialize;

/**  The Project Models by the slot each is chosen for; a slot without one uses the general settings' Model. */
export type ProjectModels_Deserialize = {
	transcription?: ModelSource | null,
	translation?: ModelSource | null,
};

/**  The Project Models by the slot each is chosen for; a slot without one uses the general settings' Model. */
export type ProjectModels_Serialize = {
	transcription: ModelSource | null,
	translation: ModelSource | null,
};

/**  What the user sets for one Project in the settings beside its Primary Language. */
export type ProjectOptions = ProjectOptions_Serialize | ProjectOptions_Deserialize;

/**  What the user sets for one Project in the settings beside its Primary Language. */
export type ProjectOptions_Deserialize = {
	/**  The Project Name the user gave, or none to name the Project after its directory. */
	name?: string | null,
	bilingual_order?: BilingualOrder,
	/**  Whether each translation keeps a Bilingual SRT beside it, written with either of its texts. */
	is_bilingual_autosaved?: boolean,
	/**  Whether a subtitle about to be overwritten is first kept as a Backup. */
	is_overwrite_backed_up?: boolean,
	/**  Whether the transcribe dialog asks to diarize the Resource once transcribed. */
	is_diarized_after_transcription?: boolean,
	models?: ProjectModels_Deserialize,
	transcription?: TranscriptionOverrides,
};

/**  What the user sets for one Project in the settings beside its Primary Language. */
export type ProjectOptions_Serialize = {
	/**  The Project Name the user gave, or none to name the Project after its directory. */
	name: string | null,
	bilingual_order: BilingualOrder,
	/**  Whether each translation keeps a Bilingual SRT beside it, written with either of its texts. */
	is_bilingual_autosaved: boolean,
	/**  Whether a subtitle about to be overwritten is first kept as a Backup. */
	is_overwrite_backed_up: boolean,
	/**  Whether the transcribe dialog asks to diarize the Resource once transcribed. */
	is_diarized_after_transcription: boolean,
	models: ProjectModels_Serialize,
	transcription: TranscriptionOverrides,
};

export type ProjectView = ProjectView_Serialize | ProjectView_Deserialize;

export type ProjectView_Deserialize = {
	directory: string,
	name: string,
	/**  The name the Project takes from its directory without a Project Name of its own. */
	directory_name: string,
	language: Language,
	translation_language: Language | null,
	options: ProjectOptions_Deserialize,
	translation_glossary: TranslationGlossaryView | null,
	resources: ResourceView[],
	current_resource: string | null,
	media: string | null,
	segments: Segment_Deserialize[],
	/**  The Glossary Marks of each of `segments`. */
	glossary_marks: SegmentGlossaryMarks[],
	shown_translation: Language | null,
	/**
	 *  What the Translation Glossary calls each Speaker in the translation shown, by its name in
	 *  the Primary Language, so the webview names a Speaker as the saved subtitle does.
	 */
	shown_speaker_names: { [key in string]: string },
	has_undo: boolean,
	has_redo: boolean,
	running_mode: RunningMode | null,
	pending_batch: SegmentSpan | null,
	/**
	 *  Which Preset Model each Project Model is; the Preset Models belong to the toolchain, so the
	 *  command answering the view fills this in.
	 */
	project_model_presets: ProjectModelPresets,
};

export type ProjectView_Serialize = {
	directory: string,
	name: string,
	/**  The name the Project takes from its directory without a Project Name of its own. */
	directory_name: string,
	language: Language,
	translation_language: Language | null,
	options: ProjectOptions_Serialize,
	translation_glossary: TranslationGlossaryView | null,
	resources: ResourceView[],
	current_resource: string | null,
	media: string | null,
	segments: Segment_Serialize[],
	/**  The Glossary Marks of each of `segments`. */
	glossary_marks: SegmentGlossaryMarks[],
	shown_translation: Language | null,
	/**
	 *  What the Translation Glossary calls each Speaker in the translation shown, by its name in
	 *  the Primary Language, so the webview names a Speaker as the saved subtitle does.
	 */
	shown_speaker_names: { [key in string]: string },
	has_undo: boolean,
	has_redo: boolean,
	running_mode: RunningMode | null,
	pending_batch: SegmentSpan | null,
	/**
	 *  Which Preset Model each Project Model is; the Preset Models belong to the toolchain, so the
	 *  command answering the view fills this in.
	 */
	project_model_presets: ProjectModelPresets,
};

/**  A Recent Project as the start screen and the Open menu list it, by its Project Name. */
export type RecentProjectView = {
	directory: string,
	name: string,
	opened_at_ms: number,
};

/**
 *  What to look for in a text and what to put in its place. Rust reads the pattern, so a regular
 *  expression means the same whatever the webview's engine would make of it.
 */
export type Replacement = {
	pattern: string,
	/**  Put in place of each match; groups of a regular expression are named as `$1` or `${name}`. */
	substitute: string,
	/**  Whether `pattern` is a regular expression rather than text taken as written. */
	is_regex: boolean,
};

/**  A file of a Hugging Face Repository, by its path in the Repository. */
export type RepositoryFile = {
	path: string,
	size: number,
};

/**  A Resource as the Resource list shows it. */
export type ResourceView = {
	name: string,
	has_media: boolean,
	has_subtitle: boolean,
	translation_languages: Language[],
};

/**
 *  What a restore or a translation left behind: how many Segments of the original have times
 *  that no translation lines up with.
 */
export type Restoration = {
	unmatched_count: number,
};

/**  Which part of a Comparison Row to take back. */
export type RevertPart = "text" | "times" | "whole";

/**  How the cues of a Comparison Row stand to each other. */
export type RowKind = "pair" | "addition" | "removal" | "split" | "merge";

/**  A Mode running on one Resource, and so which of its subtitles nothing else may change. */
export type RunningMode = 
/**  Holds every subtitle of the Resource. */
{ mode: "transcription" } | 
/**  Holds every subtitle of the Resource, as it gives each its Speakers. */
{ mode: "diarization" } | 
/**
 *  Holds only the translation into `language`, or only its Segments at `indexes` while they
 *  are translated again.
 */
{ mode: "translation"; language: Language; indexes: number[] | null };

/**  What to look for in the texts, read as a Replacement's `pattern` is. */
export type Search = {
	pattern: string,
	is_regex: boolean,
};

export type Segment = Segment_Serialize | Segment_Deserialize;

/**
 *  A change to the Segments themselves, by position, made alike to the original and each translation.
 * 
 *  Segments may overlap, as when someone cuts in, but keep the order they start in: a Segment a
 *  change makes takes its place by its start, and a change that would start one before the
 *  Segment before it or after the one after it is refused.
 */
export type SegmentChange = { kind: "times"; index: number; start_ms: number; end_ms: number } | 
/**  The end of the Segment at `index` and the start of the next, moved together to `at_ms`. */
{ kind: "boundary"; index: number; at_ms: number } | 
/**  An empty Segment from `start_ms` to `end_ms`, placed among the others by its start. */
{ kind: "insertion"; start_ms: number; end_ms: number } | 
/**
 *  An empty Segment filling the gap before the one at `index`, or running `INSERTED_MS` up to
 *  its start where there is none.
 */
{ kind: "insertion-before"; index: number } | 
/**
 *  An empty Segment filling the gap after the one at `index`, or running `INSERTED_MS` from its
 *  end where there is none.
 */
{ kind: "insertion-after"; index: number } | 
/**  The Segments at `indexes`, in any order. */
{ kind: "deletion"; indexes: number[] } | 
/**
 *  Two Segments, split after the `at`th character of the text; the translation stays with the
 *  first, and the second takes its place by its start.
 */
{ kind: "split"; index: number; at: number } | 
/**
 *  One Segment from `first` through the latest end of `first` through `last`, their texts and
 *  translations each joined on one line, with a half-width space where either side of a join is a
 *  half-width letter or digit.
 */
{ kind: "merge"; first: number; last: number } | 
/**  `first` through `last` moved by `offset_ms`, stopping at the start of the media. */
{ kind: "shift"; first: number; last: number; offset_ms: number };

/**  Which text of a Segment an edit replaces. */
export type SegmentField = "text" | "translation" | 
/**  Written to the original and the translation shown; an empty one leaves the Segment with none. */
"speaker";

/**  The Glossary Marks of one Segment's text and of its translation shown. */
export type SegmentGlossaryMarks = {
	text: GlossaryMark[],
	translation: GlossaryMark[],
};

/**  The Segments from `first` through `last`, by position. */
export type SegmentSpan = {
	first: number,
	last: number,
};

export type Segment_Deserialize = {
	start_ms: number,
	end_ms: number,
	/**  Who says it, written as a Speaker Label before its text and its translation. */
	speaker?: string,
	text: string,
	translation?: string,
};

export type Segment_Serialize = {
	start_ms: number,
	end_ms: number,
	/**  Who says it, written as a Speaker Label before its text and its translation. */
	speaker?: string,
	text: string,
	translation?: string,
};

export type SlotView = {
	source: ModelSource | null,
	/**  Where the Model is expected. */
	path: string | null,
	has_file: boolean,
	extensions: string[],
	/**  Which of the slot's Preset Models the Model is, as its place among them. */
	preset_index: number | null,
};

export type SpanKind = "common" | "removal" | "addition";

/**
 *  The system asked to open an SRT file while Tsuzuri runs; the webview takes it with
 *  `take_requested_srt`.
 */
export type SrtRequested = null;

/**  The Backups of one subtitle of the Current Resource: its original, or its translation into `language`. */
export type SubtitleVersions = {
	language: Language | null,
	backups: Backup[],
};

/**  Where a Search matches: characters `start` to `end` of the Segment at `index`. */
export type TextMatch = {
	index: number,
	start: number,
	end: number,
};

/**  A run of characters of a Pair's text, and which Version has it. */
export type TextSpan = {
	kind: SpanKind,
	text: string,
};

export type Transcription = {
	audio_seconds: number,
	transcribe_seconds: number,
	phases: PhaseTiming[],
	/**  The positions of the Segments written within an Audio Window, none for the whole media file. */
	written_span: SegmentSpan | null,
};

/**  The Transcription Settings a Project sets for itself; one left `None` follows the general settings. */
export type TranscriptionOverrides = {
	has_vad: boolean | null,
	is_non_speech_suppressed: boolean | null,
	is_context_carried: boolean | null,
	is_simplified_cleaned: boolean | null,
};

/**
 *  Which Segments a transcription replaces, by the positions the Current Resource shows: every
 *  one, those from `first` on to the media's end, or those of a span.
 */
export type TranscriptionScope = ({ kind: "whole" }) & { first?: never } | { kind: "rest"; first: number } | {
	kind: "span",
} & SegmentSpan;

/**
 *  How a transcription runs beyond the Language and the Model, saved across launches as the default
 *  of every Project. The defaults leave whisper-cli as it behaves on its own and clean what it
 *  writes in `zh-TW`.
 */
export type TranscriptionSettings = {
	/**  Whether VAD finds the speech first, so only that is transcribed. */
	has_vad?: boolean,
	is_non_speech_suppressed?: boolean,
	/**  Whether each window carries the text before it as context, which can repeat a mistake. */
	is_context_carried?: boolean,
	/**  Whether a Simplified Cleanup follows a transcription in `zh-TW`. */
	is_simplified_cleaned?: boolean,
};

export type Translation = {
	phases: PhaseTiming[],
	/**
	 *  How many Segments of the original, retimed while it was translated, find no cue at their
	 *  times in what was written.
	 */
	unmatched_count: number,
};

/**
 *  What the webview shows of a Translation Glossary: the file it came from, how many terms it
 *  holds, and the Speakers it names in the Primary Language.
 */
export type TranslationGlossaryView = {
	file: string,
	term_count: number,
	speakers: string[],
};

/**  The choices the Translate panel offers for one translation. */
export type TranslationOptions = {
	has_speaker_labels?: boolean,
	has_self_review?: boolean,
	/**  The Rolling Summary's word limit, or none to keep no summary. */
	summary_word_limit?: number | null,
	/**  Whether a Simplified Cleanup follows a translation into `zh-TW`. */
	is_simplified_cleaned?: boolean,
};

/**  How a translation is batched and repaired, saved across launches. */
export type TranslationSettings = {
	/**  Segments per Batch. */
	batch_size?: number,
	/**  Translated lines around a request that it carries as reference. */
	reference_lines?: number,
	/**  Requests for the same lines before a failing group is split in half. */
	retries?: number,
	/**  Whether translations run on the Resident llama-server rather than one started for each. */
	has_resident_llama?: boolean,
	/**  Seconds the Resident llama-server keeps the Model after a translation ends. */
	model_keep_seconds?: number,
	/**  Whether the Translate panel offers a Simplified Cleanup checked for a translation into `zh-TW`. */
	is_simplified_cleaned?: boolean,
};

/**  Where Tsuzuri looks for an App Update. */
export type UpdateChannel = 
/**  The latest release. */
"stable" | 
/**  The build of each push to the trunk, which also carries each stable release. */
"preview";

/**  How much of the App Update being installed has downloaded, in bytes. */
export type UpdateProgress = {
	downloaded: number,
	total: number | null,
};

/**  Whether Tsuzuri looks for an App Update at launch, and in which Update Channel. */
export type UpdateSettings = {
	has_launch_check: boolean,
	channel: UpdateChannel,
};

/**
 *  The Video Window was asked to close and stays open until the main window's page takes its
 *  video back.
 */
export type VideoWindowClosing = null;

/**  How loud a media file is over time, one Peak for each `1 / peaks_per_second` of it. */
export type Waveform = {
	/**  The media file it was taken from, so an answer for a Resource no longer current is told apart. */
	media: string,
	peaks_per_second: number,
	peaks: number[],
};

/**  Which text each cue of an SRT, or each block of a Plain Text, carries. */
export type WrittenText = "original" | 
/**  A Segment not yet translated keeps its original text, so no cue is left empty. */
"translation" | 
/**  The original above the translation in the same cue. */
"bilingual";

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

